### ISSUE TITLE
Shadowbringers (5.0) Actions and Recipes

### ISSUE THREAD

**Issue by MrFluffums** [doxxx/ffxiv-craft-opt-web#272]
All 5.0 recipes are missing from the crafting solver, and several actions need removed or changed in their placement. For example, all of the "Brand of [Element]" and "Name of [Element]" actions have been removed along with Byregot's Brow, and Byregot's Blessing and Steady Hand II are now innate skills and no longer cross-class actions, despite showing up in the cross-class macro generation.

Further, recipes over level 70 are not present.

Other changes may include calculations for recipe difficulty over 70, although the calculations for progress/quality seem accurate when using the solver for recipes =<70 even with gear >70.

**Comment by shdpdx85** [comment]
There are also new foods e.g. blood bouillabaise which are not in the database for buff purposes.

**Comment by Sanaki** [comment]
There were a few minor adjustments as well, such as Inner Quiet and Innovation having a combined control cap of 3000, all specialist heart skills being limited to five uses per recipe, and Muscle Memory and Piece by Piece being capped at 1000 progress. I'm not certain if there were any others beyond those.

**Comment by doxxx** [comment]
I have scraped the new recipes but I had to guess at the effective levels. However, my source for food/medicine buffs no longer works and I need to rewrite that code to use a new source.

**Comment by doxxx** [comment]
I've uploaded the updated recipe database to the beta site. This includes things like level 71-80 recipes, the removal of elemental aspects and other new and changed recipes in the 1-70 range.

Let me know if the effective level for the 71-80 recipes seems off.

**Comment by tyrone-sudeium** [comment]
Suspect the scraper has some kind of issue, most of the 71-80 recipes are still missing. For example, in-game the Blacksmith 71-75 has 56 new recipes, like this:

![image](https://user-images.githubusercontent.com/819705/60749964-1e86f900-9fe5-11e9-9d09-309a48595472.png)

**Comment by doxxx** [comment]
Yeah, there was another change I had to make to the scraper. It's running again now but it takes a while since the Lodestone server throttles how fast it can load pages. I'll probably be able to update it tomorrow morning.

**Comment by ikoyy** [comment]
I feel stupid, where can I find the beta site to try out the 5.0 algorythms?

**Comment by doxxx** [comment]
http://ffxiv-beta.lokyst.net/

**Comment by Critical-Impact** [comment]
I know this is a separate issue but at least somewhat related to 5.0
My level is now above 70 and I cant set my level to be above 70 in the attributes section.

**Comment by shdpdx85** [comment]
Another item not yet addressed is the various 'elemental' brands and names have been consolidated into one of each, "Name of the Elements" and "Brand of Elements." Appears to be available to all job types at level requirements, so not required to be a cross-class action.

![image](https://user-images.githubusercontent.com/52354717/60768660-47f26400-a07b-11e9-97d5-eef17bd84ad5.png)

**Comment by doxxx** [comment]
More recipes should be available now and I've increased the max level in the attributes page.

**Comment by doxxx** [comment]
Name/Brand of the Elements poses a bigger problem. Some countries like China are not on patch 5.0 yet AFAIK (@kongspark can you confirm?), so I can't simply remove the Name/Brand of Wind/Water/etc. actions. One solution would be to introduce a setting for patch level, which is a significant change that will take some time. I could add Name/Brand of the Elements in the meantime, but the solver won't know to avoid the old Name/Brand actions.

**Comment by doxxx** [comment]
Although, I just realized that the recipe updates have removed elemental aspects so that's broken it partially for China already. :P

**Comment by doxxx** [comment]
For the Chinese players, I've deployed the latest patch 4.x compatible code to the [main site](https://ffxiv.lokyst.net) and will continue deploying patch 5.0 changes to the beta site.

**Comment by unfaiyted** [comment]
Hey @doxxx have you considered changing the source of recipes mined from the ffxiv-datamining CSV's shouldn't have any issues with parsing that and getting all that data points, could also help replace the tooltip issues. It has all the data. Alternative you could use the tools they use to extract that data directly

[ffxiv-datamining](https://github.com/viion/ffxiv-datamining/tree/master/csv)

**Comment by doxxx** [comment]
@unfaiyted That looks interesting, although the data is very noisy. Lots of weird incomplete entries. And it looks like it's missing a lot of the crafting actions.

I'm currently looking at using Garland Tools as a data source for actions. See #276.

**Comment by doxxx** [comment]
Saved synths which use removed actions should now show a ? icon instead of just an empty slot.

**Comment by ShammyLevva** [comment]
I was thinking that now the game shows the values of progress at 100% perhaps that would be useful to include on the initial display as a double check that the base calcs are right. 

I'm assuming that work needs to be done to determine the 71+ scaling levels is there anything we can do to assist determining those values?

**Comment by doxxx** [comment]
@ShammyLevva Could you post a screenshot?

**Comment by gr3ger** [comment]
He's talking about this, look at the top right.
https://i.imgur.com/GAtflSi.png

**Comment by ShammyLevva** [comment]
![image](https://user-images.githubusercontent.com/29687786/61031645-daff0700-a3b7-11e9-8f8e-e86618a4331f.png)

**Comment by gr3ger** [comment]
Another option would be a way to override the quality/progress calculation by inputting the values the game gives you for a more accurate solve, until we have figured out the algorithm properly

**Comment by ShammyLevva** [comment]
Yes but the issue with that is the numbers can and do change after certain skills are used - eg: when you use a skill that buffs the quality. So changing the starting progress/quality numbers whilst potentially useful for debugging doesn't help understand how the figures are derived by the game and how the skills used affect it because you'd not be able to change inaccurate values mid way through a skill sequence.

**Comment by doxxx** [comment]
This does give us a non-destructive way to collect data from the game about the relationships between the various attributes, levels, etc.

**Comment by gr3ger** [comment]
@ShammyLevva 
That is already handled, the most inaccurate thing about the solver right now is the base progress/quality calculation

**Comment by ShammyLevva** [comment]
@gr3ger yup hence my suggestion that with this info on the page and the info in game it would be possible to do a data collection exercise and actively test different functions solver vs game to see if there was an identifiable pattern that could lead to fixes and more accuracy.

It might also allow better reporting by users if they can say I did X and it indicated Y but in game it said Z.

**Comment by doxxx** [comment]
To do that we will need to know the "effective crafter level" for levels 71-80. This is the current table:

```
    51: 120,
    52: 125,
    53: 130,
    54: 133,
    55: 136,
    56: 139,
    57: 142,
    58: 145,
    59: 148,
    60: 150,
    61: 260,
    62: 265,
    63: 270,
    64: 273,
    65: 276,
    66: 279,
    67: 282,
    68: 285,
    69: 288,
    70: 290 
```

With the values for 71-80, I should be able to calculate the base progress & quality amounts using our current formula a display those like you suggested.

**Comment by ShammyLevva** [comment]
Happy to help - how do we go about determining those figures? They look a bit like the average gear level for an item at that level?

**Comment by doxxx** [comment]
One way is to take the existing base progress/quality formula and using an actual progress/quality value from the game plug those values along with craftsmanship/control into the formula to determine the crafter to recipe level difference that would result in that value. Basically, reformulate the equation such that level difference is the output instead of the base progress/quality value.

That only applies if the coefficients for the current tier are correct for the new level range. If not, then we'll need a bunch of progress/quality values with corresponding crafter level, recipe level, craftsmanship and control, and apply the Excel solver (😄) to the data to determine the effective crafter levels and coefficients. This requires a broad set of data from different crafters to cover enough variation to achieve a good fit.

**Comment by doxxx** [comment]
@ShammyLevva's changes have been deployed to the beta site.

**Comment by doxxx** [comment]
Note that the new actions have placeholder icons and are not actually distinguishable yet. I need to add simple name tooltips to replace the XIVDB tooltips.

**Comment by doxxx** [comment]
I've implemented replacement action tooltips with all the basic information.

**Comment by gr3ger** [comment]
I don't really get how you want us to fill in the table.
Don't we need: crafter level, craftmanship, control and level of recipe to be able to determine the correct values?

**Comment by doxxx** [comment]
Yes, see my description above.

**Comment by gr3ger** [comment]
I'm still not a hundred percent sure what the second value in the table is.

But if you want I can give you some samples from my different crafters and
different recipes, and then skew the stats by equipping different gear.

Ironically, math isn't my strong suit.

**Comment by ShammyLevva** [comment]
Given the gearing I suspect the following values:
71 is 330, 
74 is 370,
77 is 400,
80 is 430.

These all seem consistent with previous levels. Interpolating thus gives...
71=330,
72=343,
73=357,
74=370,
75=380,
76=390,
77=400,
78=410,
79=420,
80=430.

I've stuck that in a pull request so you can import them. I'm not sure what Ing1RecipeLevelTable & Ing2RecipeLevelTable values are for though?

If you can add the display values for 100% progress and 100% quality to the beta site as suggested above. We can then compare to see if the projected values from this interpolated values match in game.

**Comment by doxxx** [comment]
The beta site now shows 100% efficiency values for progress and quality. These values will obviously be wrong for levels 71-80.

I've created a branch (dev/272-level-71-80-model) with the proposed effective crafter levels, which you should be able to try out with a local copy of the site.

**Comment by doxxx** [comment]
We have a new set of formulas for progress and quality increase. These changes are available on the beta site (ffxiv-beta.lokyst.net). Please let me know if these discrepancies are resolved.
