### ISSUE TITLE
Let us manually enter the 100% craftsmanship/quality values we can see in game?

### ISSUE THREAD

**Issue by ciel115** [doxxx/ffxiv-craft-opt-web#298]
As a patch with new master books is imminent and this site hasn't generated accurate numbers since maybe 3-star lvl 70 crafts, would it be reasonable to ask for a temporary override feature while the formulae are sorted? Like when we select a recipe, let us input the values the game now tells us for how much craftsmanship or quality we can expect at 100% for a given recipe. 

It's far from ideal because, if we plan to use food/medicine, we'll have to consume some just to make sure the numbers we input on the site are accurate before we try to build rotations (speaking more for simulator users than solver ones), but I think better than nothing. 

It would at least make the tool usable for endgame crafting in the meantime, even if at a little more inconvenience to the user. Thanks.

**Comment by ShammyLevva** [comment]
Can you advise where you have posted data with your observed values so that the collective knowledge of what values the game is giving for different gear levels can be collected.

Without data from beta testers the site will never be updated. I assume you are using the beta test site and not the patch 4.5 live site of course. 

Users that don't participate in beta testing to provide data are not helping improve the situation. So things will never get better if data isn't provided.

**Comment by ciel115** [comment]
I did eventually find, buried in a 2-week old issues post, information about what data is needed, and I will contribute although I'll be limited to lvl 80, but part of my lack of confidence comes from how it wasn't easy to find that information or any news about the state of the app, what you guys need, how we can help etc. 

I still don't know where to link a spreadsheet of data if I make one.

The "Blog" link leads to a 404 error. 

There could be a notice at the top of the app like "new recipes aren't yet calibrated, click here for info about how you can help".

**Comment by ShammyLevva** [comment]
Yet I'm using the formula's on the beta site and they are within a couple of points all the time. Certainly good enough to use so again are you using the beta site?

**Comment by ciel115** [comment]
I am using the beta site, the numbers for lvl 78 and lower crafts look pretty close. lvl 80 (no stars) seems to be way off, for example I'm looking at the Onyx recipe for gsm and my in-game progress/quality are 345/374 and the app thinks it will be 476/762. 

The 1-star lvl 80 100% numbers are pretty close, although when I made a titania shadow box a few days ago i found that ingenuity 2 improved progress vastly more than the app thought it would. 

Though I suppose interactions of skills like ingenuity wouldn't be fixed by manually entering our in-game 100% numbers.

**Comment by ShammyLevva** [comment]
Thanks yes the 80 star items haven't got any values in the sim yet. 

What we need is for level 80 crafters to give the following three values:
Craftsmanship, Control, (Specialist yes/no), then for the following list progress & quality in game values
80 no stars progress & quality
80 one star progress & quality
80 two stars progress & quality
80 three stars progress & quality
80 four stars progress & quality

From these values for as big a range of craftsmanship and quality as you can manage we can devise values for the level 80 recipes. My own crafter just hit 80 in one discipline but I've not seen the star recipes yet. I'm assuming I need to grind scrips and buy the book as usual.

**Comment by ciel115** [comment]
I'd be happy to contribute some data, if I make up a spreadsheet do you just want me to link to it here or is there somewhere better that you're collecting data?

**Comment by ciel115** [comment]
Here's some progress data for lvl 80/1star/2star, non specialist. 

https://docs.google.com/spreadsheets/d/1oxnNZTykWPvegDcV_Co1ixYjruBB9UNsPAzf9WuifeY/edit?usp=sharing

I'll try to do the same with quality sometime within the next few days.

Does being a specialist have an effect on these values other than the stats added by the soul crystal?

**Comment by ShammyLevva** [comment]
That's helpful thanks. Still an issue getting the values matching. 

I'm thinking something like this
![image](https://user-images.githubusercontent.com/29687786/62213331-948b3f80-b39a-11e9-996e-8ae4a9f72580.png)

So simulator populates boxes on update of page and uses those values if different from calculated ones.

**Comment by ShammyLevva** [comment]
I've reworked a lvl 80 formula based on the values you submitted and my own values. The result is pretty good - I don't know about star recipes as I've not purchased them yet.

Quality figures are wildly out though and need data to tweak them.

**Comment by Sonin** [comment]
Hopefully this is the right place to submit this, but here's 35 sets of data for lv80 0 / 1 / 2 star values, both progress and quality. 

https://docs.google.com/spreadsheets/d/1HQWWNjee0ZlxPKT0AqDtHGXENsXWjKDMe2AFuzp3UNA/edit?usp=sharing

**Comment by ShammyLevva** [comment]
Beta site updated with formulae based on these figures and others provided. Quality and Progress should be much closer to in game. Ingenuity figures still need tweaked for star recipes.

**Comment by doxxx** [comment]
We have a new set of formulas for progress and quality increase. These changes are available on the beta site (ffxiv-beta.lokyst.net). Please let me know if these discrepancies are resolved.
