### ISSUE TITLE
Double Inner Quiet

### ISSUE THREAD

**Issue by Thortok** [doxxx/ffxiv-craft-opt-web#84]
![image](https://cloud.githubusercontent.com/assets/14281289/10036272/51560290-6173-11e5-9e59-ec50c008c9e0.png)

This is happening fairly often on level 13-ish crafters that don't have much in the way of abilities.  Seems like a waste of cp for calculation purposes as the 2nd one can't actually cast in-game.

**Comment by Thortok** [comment]
This doesn't really do much either:

![image](https://cloud.githubusercontent.com/assets/14281289/10059478/2a499170-6219-11e5-9726-322cc917cb73.png)

**Comment by doxxx** [comment]
I just updated the beta site with a bunch of changes for the solver. In addition to improvements for the current eaSimple algorithm, there's also a new eaComplex algorithm. Please try both and let me know if either performs any better.

Blog post with more info: http://ffxiv.lokyst.net/blog/?p=129

**Comment by Thortok** [comment]
Will do!  Thanks and keep up the good work!  =D

**Comment by Thortok** [comment]
The complex one seems to generate a result faster, which is sweet.  However I notice that sometimes after clicking 'solve' on the simulator page, it stutters and then stops on 0.  Even clicking 'start' can cause it to stutter and stop.  If I keep trying and clicking 'start' a few times eventually it begins calculating and finds a result.  I haven't tried simple yet to see if it has the same 'failure to launch' effect.

So far complex hasn't had any severe issues, although I have seen it use the 'observe' move a couple times which I'm not sure what the point is.  The only blatantly wasted move I've seen so far is this one:

![image](https://cloud.githubusercontent.com/assets/14281289/10117123/6a72cc8c-641a-11e5-9bb6-068f0fb651ae.png)

There's no need to recover cp if the very next move completes the craft without using CP, so what's the point of Rumination?

Also, the old site would say 'these are the cross-class skills you need to equip.'  The new icons on the abilities help but I miss the old way.

**Comment by Thortok** [comment]
In regards to the complex 'failure to launch' effect, I notice it happens more often for lower level recipes (like hempen yarn) and sometimes it's so bad that it can be near 30 seconds of clicking 'start' over and over again until it finally works.  Really hope that gets fixed soon, otherwise I tend to use simple.  It may be slower to calculate but it works every time.

**Comment by doxxx** [comment]
Regarding the "stutter and stop" issue, it would be helpful if you could note the crafter stats, recipe and seed number (in the solver log tab). That should allow me to reproduce it and see what the problem is.

Regarding Observe, if the solver is putting it there, it must have had some beneficial effect. It's usually an indication that waiting for a Good or Excellent condition at that point will produce a much better result. Since conditions are random, it should be considered more of a guideline. If it bothers you, the action can be disabled in the Crafter Attributes page.

Regarding Rumination at the end, one of the goals of the solver is to maximize remaining CP, after maximizing quality and progress, but before minimizing sequence length. So, according to the "rules" of the solver, this is a better solution than one without Rumination. :) However, I will try swapping the order of the goals so that it will try to minimize sequence length before maximizing CP and see if that produces reasonable results.

**Comment by doxxx** [comment]
Actually, do you see this error in the browser's Javascript console when you encounter the "stutter and stop" issue?

```
TypeError: Cannot read property 'successProbability' of undefined
    at ApplyModifiers (http://localhost:8001/js/ffxivcraftmodel.js:368:36)
    at simSynth (http://localhost:8001/js/ffxivcraftmodel.js:788:17)
    at evalSeq (http://localhost:8001/js/ffxivcraftmodel.js:1374:18)
    at evalSeqWrapper (http://localhost:8001/js/solver/worker.js:140:12)
    at (anonymous function) (http://localhost:8001/lib/yagal/toolbox.js:64:17)
    at Array.map (native)
    at Toolbox.map (http://localhost:8001/lib/yagal/toolbox.js:51:16)
    at Object.ALGORITHMS.eaComplex.gen (http://localhost:8001/js/solver/eacomplex.js:38:35)
    at runOneGen (http://localhost:8001/js/solver/worker.js:206:31)
    at DedicatedWorkerGlobalScope.self.onmessage (http://localhost:8001/js/solver/worker.js:30:7)
```

**Comment by doxxx** [comment]
I believe I've fixed the "stutter and stop" issue with the eaComplex algorithm. Please force-reload the beta site and try it out.

**Comment by doxxx** [comment]
I experimented with minimizing sequence length before maximizing CP, and for the same seed it produced a lower-quality sequence. If I were to theorize, I'd say that the original goal ordering retained sequences in earlier generates that had more CP at the end, which allowed them to be extended with more quality-increasing actions in later generations.

**Comment by Thortok** [comment]
One of the ways in which your magic 8 ball thing would be an improvement is that I often see (especially with low level recipes) way more quality than is needed in order to get 100% hq.  Obviously some of that is based on potential for the touches to fail, but sometimes it does seem rather excessive.  However with the 8 ball thing, it would recognize 'oh hey you're already at max quality, how about we wrap this up now' kind of thing.

Looking forward to seeing the stutter and stop issue fixed, but if it happens again I can definitely check console for you.

To a certain extent, finishing with more CP seems to have some confirmation-bias effect on achieving HQ even when the 'official' chance for HQ is low.  Plural of anecdote is not data though but I've seemed to notice I get HQ even when below 50% four out of five times it 'ends with with a Rumination'.  Weird.

Perhaps instead of relying on a shortening priority in the generations, instead a 'cleanup check' could be run on the final result, purging things like double inner quiet and wasted ruminations.  Check for wasted actions, remove or fix, then as a final double check compare if the result is the same as before the cleanup in terms of reliability, etc.

I would actually like to see finishing with higher durability be a goal for the solver as well (if it isn't already), especially on any sequence that fails to achieve 100% reliability.  The more durability it leaves after the sequence the more likely a later generation can achieve 100% reliability and/or the user achieve it manually, if possible.  This kind of goes hand in hand with the CP thing, the more durability and CP you have, the more you get to mess around, basically.

Also, sorry to toss so many different issues into one thread, I know that's probably irksome, but you skipped over the cross-class question.  I like the icons and want them to stay (although goldsmith on Manipulation is a little hard to see), but as it is now, I have to briefly scan every icon in the solution to see which class skills (if any) are present so I can make sure to have them enabled before crafting.  Is there any way we can clearly say 'these are the cross class skills that will be used' sort of like the non-beta site currently does?

**Comment by Thortok** [comment]
Stutter and stop still an issue.  Error is similar to the one you copied:

TypeError: Cannot read property 'successProbability' of undefined
    at ApplyModifiers (http://ffxiv-beta.lokyst.net/js/ffxivcraftmodel.js:368:36)
    at simSynth (http://ffxiv-beta.lokyst.net/js/ffxivcraftmodel.js:788:17)
    at evalSeq (http://ffxiv-beta.lokyst.net/js/ffxivcraftmodel.js:1374:18)
    at evalSeqWrapper (http://ffxiv-beta.lokyst.net/js/solver/worker.js:141:12)
    at (anonymous function) (http://ffxiv-beta.lokyst.net/lib/yagal/toolbox.js:64:17)
    at Array.map (native)
    at Toolbox.map (http://ffxiv-beta.lokyst.net/lib/yagal/toolbox.js:51:16)
    at Object.ALGORITHMS.eaComplex.gen (http://ffxiv-beta.lokyst.net/js/solver/eacomplex.js:38:35)
    at runOneGen (http://ffxiv-beta.lokyst.net/js/solver/worker.js:207:31)
    at start (http://ffxiv-beta.lokyst.net/js/solver/worker.js:202:3)self.onmessage @ js/solver/worker.js:36

L16 Leatherworker, 112 craft, 110 control, 243 cp, 0 starting quality, recipe is 'hard leather'

Happens when clicking 'solve' from the simulator page, and then even if I click 'start' on the solver page it continues to happen.  Apparently 9th time's the charm as it finally worked.

Did a force refresh, even closed the tab and reloaded it, as well as ended the task in my OS and reopened my browser.

Gonna do some digging in the code and see if I can help identify source of the error.

**Comment by Thortok** [comment]
Okay, I'm a bit rusty, but this is what I'm thinking is happening.

At line 368 (ffxivcraftmodel.js), ApplyModifiers function can't create a value for successProbability because it has a null.  This is what's throwing the error.  So we need to backtrace where this value is supposed to have been defined.

It creates this value based off the 2nd argument when it's called.

It's called on line 788, given the variable action.  Action is defined within the loop as the slice of the individual array that is currently being looked at within the loop.  Which means the individual array needs to contain successProbability data for every item in its array.  So where is individual defined?  It's defined as the first argument passed to the simSynth function (line 697).

Line 1374 is where simsynth is being called.  Remember that it needs to be passed an individual that contains the successProbability variable on every line of its array because eventually down the line the ApplyModifiers function is going to need that in order for all the functions above it to work.  In this case individual is defined as the first argument when the function evalSeq is called on line 1369.

evalSeq is being called on line 141 (moving to worker.js), and given the individual variable as defined as the third argument of the function evalSeqWrapper.  The wrapper is just basically changing the order of arguments.

At this point I lose the train of things.  The only other place I can find evalSeqWrapper being called is on line 154, even though that's not in the error stack.  At some point the evalSeqWrapper, when or wherever it is called, will need that 'individual' array given as the third argument when it is called, I just can't find where it's called.  Perhaps the registering of the toolbox that follows in the error stack is likely the culprit.  Somewhere along where the data finally gets passed to evalSeqWrapper, the successProbability is never defined to be included in the 'individual' array.

You could probably have figured all this out yourself faster but just trying to help.  =D

**Comment by Thortok** [comment]
Oh, forgot to provide seed number.  Seems like it changes every time I hit start.  Here's a few of them (same hard leather recipe).

138635
186993
52902
225459
155501
174670
93508
193283
113324
150082
197314

And so on.

And then when it finally worked, the seed was 191766

**Comment by doxxx** [comment]
Thanks for the seeds. FYI, they're a number used to initialize the random number generator. The Options dialog lets you set a specific seed so that you can reproduce the exact same sequence of events and random conditions. It's useful for debugging, but you should otherwise leave it off so that it uses a random seed.

I couldn't reproduce the problem with your seeds and settings. Please make sure that you force-reload the beta site to get the updates.

Since I believe the original Double Inner Quiet problem has been resolved, I'm closing this issue.
